### ISSUE TITLE
CUDA out of memory on one system but not another

### ISSUE THREAD

**Issue by 2haloes** [JoeyBallentine/ESRGAN#13]
I first reported this on n00mkrad/cupscale#91 but I have tested this script alone and the same issue occurs

On my computer (Nvidia RTX 3080 - 10GB VRAM), if I upscale images that are too big for the VRAM, the script will exit out with a CUDA out of memory exception

However, on my laptop (Nvidia RTX 3080 - 16GB VRAM) I have no issue with any images I attempt to upscale no matter the source image size and model

If I was to guess, it's something to do with the 10GB of VRAM, sadly I don't have more Nvidia cards to throw at this to test it further.

**Comment by 2haloes** [comment]
The stack trace is different so it looks like the fix did work and this is throwing the same exception message 

```Traceback (most recent call last):
  File "C:\Users\2haloes\Documents\esrgan\utils\dataops.py", line 45, in auto_split_upscale
    result = upscale_function(lr_img)
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 532, in upscale
    output = self.process(img)
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 289, in process
    output = self.model(img_LR).data.squeeze(0).float().cpu().clamp_(0, 1).numpy()
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\architecture.py", line 118, in forward
    x = self.model(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 92, in forward
    output = x + self.sub(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 317, in forward
    out = self.RDB2(out)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 432, in forward
    x5 = self.conv5(torch.cat((x, x1, x2, x3, x4), 1))
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Python39\lib\site-packages\torch\nn\modules\conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 658, in <module>
    app()
  File "C:\Python39\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python39\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 654, in main
    upscale.run()
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 237, in run
    rlt, depth = ops.auto_split_upscale(
  File "C:\Users\2haloes\Documents\esrgan\utils\dataops.py", line 51, in auto_split_upscale
    torch.cuda.empty_cache()
  File "C:\Python39\lib\site-packages\torch\cuda\memory.py", line 114, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: out of memory

**Comment by JoeyBallentine** [comment]
Wtf, it's running out of memory when clearing the memory... Could you try updating pytorch?

**Comment by 2haloes** [comment]
I've updated pytorch and the issue still occurs however it also now came with a suggestion to set an env variable (CUDA_LAUNCH_BLOCKING = 1) so I did that and it came back with this exception which looks a lot more useful

```
Traceback (most recent call last):
  File "C:\Users\2haloes\Documents\esrgan\utils\dataops.py", line 46, in auto_split_upscale
    result = upscale_function(lr_img)
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 538, in upscale
    output = self.process(img)
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 295, in process
    output = self.model(img_LR).data.squeeze(0).float().cpu().clamp_(0, 1).numpy()
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\architecture.py", line 118, in forward
    x = self.model(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 92, in forward
    output = x + self.sub(x)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 317, in forward
    out = self.RDB2(out)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\2haloes\Documents\esrgan\utils\block.py", line 432, in forward
    x5 = self.conv5(torch.cat((x, x1, x2, x3, x4), 1))
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python39\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Python39\lib\site-packages\torch\nn\modules\conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 192, 1080, 1920], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(192, 64, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0000015321CA4A30
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 192, 1080, 1920,
    strideA = 398131200, 2073600, 1920, 1,
output: TensorDescriptor 0000015321CA58A0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 64, 1080, 1920,
    strideA = 132710400, 2073600, 1920, 1,
weight: FilterDescriptor 0000015369D70F00
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 192, 3, 3,
Pointer addresses:
    input: 0000000CBB400000
    output: 0000000C3C960000
    weight: 0000000B0CF6B000
Forward algorithm: 1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 664, in <module>
    app()
  File "C:\Python39\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python39\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 660, in main
    upscale.run()
  File "C:\Users\2haloes\Documents\esrgan\upscale.py", line 243, in run
    rlt, depth = ops.auto_split_upscale(
  File "C:\Users\2haloes\Documents\esrgan\utils\dataops.py", line 58, in auto_split_upscale
    raise RuntimeError(e)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 192, 1080, 1920], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(192, 64, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0000015321CA4A30
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 192, 1080, 1920,
    strideA = 398131200, 2073600, 1920, 1,
output: TensorDescriptor 0000015321CA58A0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 64, 1080, 1920,
    strideA = 132710400, 2073600, 1920, 1,
weight: FilterDescriptor 0000015369D70F00
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 192, 3, 3,
Pointer addresses:
    input: 0000000CBB400000
    output: 0000000C3C960000
    weight: 0000000B0CF6B000
Forward algorithm: 1
```

**Comment by JoeyBallentine** [comment]
This is super weird, I've never seen this happen for inference before.

My next suggestion would just be to update your drivers and restart your computer and see if it still happens. I've had a similar error when training before and I just needed to restart my PC.

**Comment by 2haloes** [comment]
Looks like updating to CUDA 11.5 has resolved the issue

While the error can still occur if things go too over the top (64x a 1080P image) it looks like enabling the env variable stops things from getting out of hand enough to cause the script to stop

**Comment by JoeyBallentine** [comment]
64x on a 1080p image? That's a bit overkill lol. Glad it works now though
